# H2 configuration reference : https://www.baeldung.com/spring-boot-h2-database
server:
  port: 8080

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:h2:file:./lucky-db
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  h2:
    console.enabled: true
    console.path: /h2-console
#    console.settings.trace: false
#    spring.h2.console.settings.web-allow-others: false
logging.level:
  org.hibernate.SQL: debug
#
#eureka:
#  instance:
#    instance-id: product-microservice-instance
#
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#

